<?php

class td_block1_widget extends td_block_widget {
    var $td_block_id = 'td_block_1'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block1_widget");'));

class td_block2_widget extends td_block_widget {
    var $td_block_id = 'td_block_2'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block2_widget");'));

class td_block3_widget extends td_block_widget {
    var $td_block_id = 'td_block_3'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block3_widget");'));

class td_block4_widget extends td_block_widget {
    var $td_block_id = 'td_block_4'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block4_widget");'));
class td_block5_widget extends td_block_widget {
    var $td_block_id = 'td_block_5'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block5_widget");'));

class td_block6_widget extends td_block_widget {
    var $td_block_id = 'td_block_6'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block6_widget");'));

class td_block7_widget extends td_block_widget {
    var $td_block_id = 'td_block_7'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block7_widget");'));
class td_block8_widget extends td_block_widget {
    var $td_block_id = 'td_block_8'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block8_widget");'));

class td_block_ad_box_widget extends td_block_widget {
    var $td_block_id = 'td_block_ad_box'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_ad_box_widget");'));

class td_block_authors_widget extends td_block_widget {
    var $td_block_id = 'td_block_authors'; // change only the block id, the rest is autogenerated
}

add_action('widgets_init', create_function('', 'return register_widget("td_block_authors_widget");'));

class td_block_author_widget extends td_block_widget {
    var $td_block_id = 'td_block_author'; // change only the block id, the rest is autogenerated
}

add_action('widgets_init', create_function('', 'return register_widget("td_block_author_widget");'));

class td_block_popular_categories_widget extends td_block_widget {
    var $td_block_id = 'td_block_popular_categories'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_popular_categories_widget");'));

class td_block_instagram_widget extends td_block_widget {
    var $td_block_id = 'td_block_instagram'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("td_block_instagram_widget");'));