<?php

class td_block1_widget extends td_block_widget {
    var $td_block_id = 'td_block_1'; // change only the block id, the rest is autogenerated
}

add_action('widgets_init', create_function('', 'return register_widget("td_block1_widget");'));


class td_block_ad_box_widget extends td_block_widget {
    var $td_block_id = 'td_block_ad_box'; // change only the block id, the rest is autogenerated
}

add_action('widgets_init', create_function('', 'return register_widget("td_block_ad_box_widget");'));